#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SQLCipherSpeed.Resource", IsApplication=true)]

namespace SQLCipherSpeed
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			Mono.Data.Sqlcipher.Resource.String.library_name = SQLCipherSpeed.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int tableLayoutResultItem = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tableRowResultItem1 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int tableRowResultItem2 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int textViewResultItemDifference = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int textViewResultItemDifferenceLabel = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int textViewResultItemEncryptedLabel = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int textViewResultItemEncryptedMs = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int textViewResultItemNormalLabel = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int textViewResultItemNormalMs = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int textViewResultItemReportName = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int textViewResultItemSql = 2131034123;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ResultItem = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int progress_text = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int run_button_text = 2130968577;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
